#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'net/http'
require 'uri'

circuit_json = File.read(ARGV[0]).chomp

uri = URI.parse('http://localhost:3000/')
request = Net::HTTP::Get.new(uri)
request.content_type = 'application/json'
request['Accept'] = 'application/json'
request.body = JSON.dump({
                           'circuit_json' => circuit_json
                         })

req_options = {
  use_ssl: uri.scheme == 'https'
}

begin
  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end

  if response.code == '200'
    puts response.body
  else
    warn "Error (code = #{response.code}). See Rails server log for details."
  end
rescue StandardError => e
  warn e
end
